# Generated by Django 3.2.5 on 2021-07-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
